### ISSUE TITLE
强大的css选择器

### ISSUE THREAD

**Issue by pengliheng** [pengliheng/pengliheng.github.io#7]
# css select
## 很早很早以前，我对css选择器的概念一直停留在  `#id`   `.class`  ，直到我看到了[mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/:active)的Pseudo-classes，即伪类class
![image](https://user-images.githubusercontent.com/14355994/37319928-2e8ff54e-26ac-11e8-8b31-e368af37f01a.png)

## `p:not(.class)`
```html
<span class='class'>不被选择</span>
<span class="bbb">选中</span>
```
### 选择第一个子元素，最后一个子元素  ，第二个子元素，强大的select选择器配合`document.querySelectorAll('p:last-child')`进行筛选简直方便极了，和正则选择字符串一样方便
```css
// 选择既中间的元素  
div ul:not(:first-child):not(:last-child) {
    background-color: #900;
}
```
### 结论，省去了大量无效class类名，id，，无效js代码。
